make-hunspell-dict: fix regression
Add mktemp template to avoid using /tmp.
Exit error when dos conversion is not found,
instead of failing over to 'cat'.

Signed-off-by: J William Piggott <elseifthen@gmx.com>

diff --git a/scowl/speller/make-hunspell-dict b/scowl/speller/make-hunspell-dict
--- a/scowl/speller/make-hunspell-dict
+++ b/scowl/speller/make-hunspell-dict
@@ -5,7 +5,8 @@ if command -v todos; then
 elif command -v unix2dos; then
  UNIX2DOS=unix2dos
 else
- UNIX2DOS=cat
+echo "Error: unix2dos or todos command not found."
+exit 1
 fi
 
 if echo $LANG | grep -i utf > /dev/null; then
@@ -52,8 +53,8 @@ deaccent() {
 }
 
 with-and-without-accents() {
-  tmp1=`mktemp`
-  tmp2=`mktemp`
+  tmp1=`mktemp tmp-XXXXXX`
+  tmp2=`mktemp tmp-XXXXXX`
   cat - > $tmp1
   deaccent < $tmp1 > $tmp2
   cat $tmp1 $tmp2
